-- Add CurrencyCode and CurrencySymbol columns to DB_Countries table
ALTER TABLE [DB_Countries] ADD [CurrencyCode] nvarchar(10) NULL;
ALTER TABLE [DB_Countries] ADD [CurrencySymbol] nvarchar(10) NULL;

-- Update currency data for all countries
UPDATE [DB_Countries] SET [CurrencyCode] = 'ALL', [CurrencySymbol] = N'Lek' WHERE [Country] = 'Albania';
UPDATE [DB_Countries] SET [CurrencyCode] = 'AOA', [CurrencySymbol] = N'Kz' WHERE [Country] = 'Angola';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ARS', [CurrencySymbol] = N'$' WHERE [Country] = 'Argentina';
UPDATE [DB_Countries] SET [CurrencyCode] = 'AMD', [CurrencySymbol] = N'֏' WHERE [Country] = 'Armenia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE [Country] = 'Australia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Austria';
UPDATE [DB_Countries] SET [CurrencyCode] = 'AZN', [CurrencySymbol] = N'₼' WHERE [Country] = 'Azerbaijan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BDT', [CurrencySymbol] = N'৳' WHERE [Country] = 'Bangladesh';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Belgium';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Benin';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BOB', [CurrencySymbol] = N'Bs' WHERE [Country] = 'Bolivia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BAM', [CurrencySymbol] = N'KM' WHERE [Country] = 'Bosnia and Herzegovina';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BWP', [CurrencySymbol] = N'P' WHERE [Country] = 'Botswana';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BRL', [CurrencySymbol] = N'R$' WHERE [Country] = 'Brazil';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BGN', [CurrencySymbol] = N'лв' WHERE [Country] = 'Bulgaria';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Burkina Faso';
UPDATE [DB_Countries] SET [CurrencyCode] = 'BIF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Burundi';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CVE', [CurrencySymbol] = N'$' WHERE [Country] = 'Cabo Verde';
UPDATE [DB_Countries] SET [CurrencyCode] = 'KHR', [CurrencySymbol] = N'៛' WHERE [Country] = 'Cambodia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Cameroon';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CAD', [CurrencySymbol] = N'$' WHERE [Country] = 'Canada';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Chad';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CLP', [CurrencySymbol] = N'$' WHERE [Country] = 'Chile';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CNY', [CurrencySymbol] = N'¥' WHERE [Country] = 'China';
UPDATE [DB_Countries] SET [CurrencyCode] = 'COP', [CurrencySymbol] = N'$' WHERE [Country] = 'Colombia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CRC', [CurrencySymbol] = N'₡' WHERE [Country] = 'Costa Rica';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Croatia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Cyprus';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CZK', [CurrencySymbol] = N'Kč' WHERE [Country] = 'Czechia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Côte d''Ivoire';
UPDATE [DB_Countries] SET [CurrencyCode] = 'DKK', [CurrencySymbol] = N'kr' WHERE [Country] = 'Denmark';
UPDATE [DB_Countries] SET [CurrencyCode] = 'DJF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Djibouti';
UPDATE [DB_Countries] SET [CurrencyCode] = 'DOP', [CurrencySymbol] = N'RD$' WHERE [Country] = 'Dominican Republic';
UPDATE [DB_Countries] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE [Country] = 'Ecuador';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EGP', [CurrencySymbol] = N'£' WHERE [Country] = 'Egypt';
UPDATE [DB_Countries] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE [Country] = 'El Salvador';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Estonia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'SZL', [CurrencySymbol] = N'L' WHERE [Country] = 'Eswatini';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ETB', [CurrencySymbol] = N'Br' WHERE [Country] = 'Ethiopia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Finland';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'France';
UPDATE [DB_Countries] SET [CurrencyCode] = 'GMD', [CurrencySymbol] = N'D' WHERE [Country] = 'Gambia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'GEL', [CurrencySymbol] = N'₾' WHERE [Country] = 'Georgia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Germany';
UPDATE [DB_Countries] SET [CurrencyCode] = 'GHS', [CurrencySymbol] = N'₵' WHERE [Country] = 'Ghana';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Greece';
UPDATE [DB_Countries] SET [CurrencyCode] = 'GTQ', [CurrencySymbol] = N'Q' WHERE [Country] = 'Guatemala';
UPDATE [DB_Countries] SET [CurrencyCode] = 'GNF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Guinea';
UPDATE [DB_Countries] SET [CurrencyCode] = 'HTG', [CurrencySymbol] = N'G' WHERE [Country] = 'Haiti';
UPDATE [DB_Countries] SET [CurrencyCode] = 'HNL', [CurrencySymbol] = N'L' WHERE [Country] = 'Honduras';
UPDATE [DB_Countries] SET [CurrencyCode] = 'HUF', [CurrencySymbol] = N'Ft' WHERE [Country] = 'Hungary';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ISK', [CurrencySymbol] = N'kr' WHERE [Country] = 'Iceland';
UPDATE [DB_Countries] SET [CurrencyCode] = 'INR', [CurrencySymbol] = N'₹' WHERE [Country] = 'India';
UPDATE [DB_Countries] SET [CurrencyCode] = 'IDR', [CurrencySymbol] = N'Rp' WHERE [Country] = 'Indonesia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Ireland';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ILS', [CurrencySymbol] = N'₪' WHERE [Country] = 'Israel';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Italy';
UPDATE [DB_Countries] SET [CurrencyCode] = 'JMD', [CurrencySymbol] = N'$' WHERE [Country] = 'Jamaica';
UPDATE [DB_Countries] SET [CurrencyCode] = 'JPY', [CurrencySymbol] = N'¥' WHERE [Country] = 'Japan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'JOD', [CurrencySymbol] = N'د.ا' WHERE [Country] = 'Jordan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'KZT', [CurrencySymbol] = N'₸' WHERE [Country] = 'Kazakhstan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'KES', [CurrencySymbol] = N'Sh' WHERE [Country] = 'Kenya';
UPDATE [DB_Countries] SET [CurrencyCode] = 'KRW', [CurrencySymbol] = N'₩' WHERE [Country] = 'Korea';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Kosovo';
UPDATE [DB_Countries] SET [CurrencyCode] = 'KGS', [CurrencySymbol] = N'с' WHERE [Country] = 'Kyrgyzstan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Latvia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'LRD', [CurrencySymbol] = N'$' WHERE [Country] = 'Liberia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Lithuania';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Luxembourg';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MGA', [CurrencySymbol] = N'Ar' WHERE [Country] = 'Madagascar';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MWK', [CurrencySymbol] = N'MK' WHERE [Country] = 'Malawi';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MYR', [CurrencySymbol] = N'RM' WHERE [Country] = 'Malaysia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Mali';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Malta';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MRU', [CurrencySymbol] = N'UM' WHERE [Country] = 'Mauritania';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MUR', [CurrencySymbol] = N'₨' WHERE [Country] = 'Mauritius';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MXN', [CurrencySymbol] = N'$' WHERE [Country] = 'Mexico';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MDL', [CurrencySymbol] = N'Lei' WHERE [Country] = 'Moldova';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MNT', [CurrencySymbol] = N'₮' WHERE [Country] = 'Mongolia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Montenegro';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MAD', [CurrencySymbol] = N'د.م' WHERE [Country] = 'Morocco';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MZN', [CurrencySymbol] = N'MT' WHERE [Country] = 'Mozambique';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MMK', [CurrencySymbol] = N'K' WHERE [Country] = 'Myanmar';
UPDATE [DB_Countries] SET [CurrencyCode] = 'NAD', [CurrencySymbol] = N'$' WHERE [Country] = 'Namibia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'NPR', [CurrencySymbol] = N'₨' WHERE [Country] = 'Nepal';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Netherlands';
UPDATE [DB_Countries] SET [CurrencyCode] = 'NZD', [CurrencySymbol] = N'$' WHERE [Country] = 'New Zealand';
UPDATE [DB_Countries] SET [CurrencyCode] = 'NIO', [CurrencySymbol] = N'C$' WHERE [Country] = 'Nicaragua';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Niger';
UPDATE [DB_Countries] SET [CurrencyCode] = 'NGN', [CurrencySymbol] = N'₦' WHERE [Country] = 'Nigeria';
UPDATE [DB_Countries] SET [CurrencyCode] = 'MKD', [CurrencySymbol] = N'ден' WHERE [Country] = 'North Macedonia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'NOK', [CurrencySymbol] = N'kr' WHERE [Country] = 'Norway';
UPDATE [DB_Countries] SET [CurrencyCode] = 'PKR', [CurrencySymbol] = N'₨' WHERE [Country] = 'Pakistan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE [Country] = 'Panama';
UPDATE [DB_Countries] SET [CurrencyCode] = 'PYG', [CurrencySymbol] = N'₲' WHERE [Country] = 'Paraguay';
UPDATE [DB_Countries] SET [CurrencyCode] = 'PEN', [CurrencySymbol] = N'S/' WHERE [Country] = 'Peru';
UPDATE [DB_Countries] SET [CurrencyCode] = 'PHP', [CurrencySymbol] = N'₱' WHERE [Country] = 'Philippines';
UPDATE [DB_Countries] SET [CurrencyCode] = 'PLN', [CurrencySymbol] = N'zł' WHERE [Country] = 'Poland';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Portugal';
UPDATE [DB_Countries] SET [CurrencyCode] = 'RON', [CurrencySymbol] = N'lei' WHERE [Country] = 'Romania';
UPDATE [DB_Countries] SET [CurrencyCode] = 'RWF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Rwanda';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Senegal';
UPDATE [DB_Countries] SET [CurrencyCode] = 'RSD', [CurrencySymbol] = N'дин' WHERE [Country] = 'Serbia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'SCR', [CurrencySymbol] = N'₨' WHERE [Country] = 'Seychelles';
UPDATE [DB_Countries] SET [CurrencyCode] = 'SLL', [CurrencySymbol] = N'Le' WHERE [Country] = 'Sierra Leone';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Slovak Republic';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Slovenia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'SOS', [CurrencySymbol] = N'Sh' WHERE [Country] = 'Somalia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ZAR', [CurrencySymbol] = N'R' WHERE [Country] = 'South Africa';
UPDATE [DB_Countries] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE [Country] = 'Spain';
UPDATE [DB_Countries] SET [CurrencyCode] = 'LKR', [CurrencySymbol] = N'Rs' WHERE [Country] = 'Sri Lanka';
UPDATE [DB_Countries] SET [CurrencyCode] = 'SEK', [CurrencySymbol] = N'kr' WHERE [Country] = 'Sweden';
UPDATE [DB_Countries] SET [CurrencyCode] = 'CHF', [CurrencySymbol] = N'CHF' WHERE [Country] = 'Switzerland';
UPDATE [DB_Countries] SET [CurrencyCode] = 'TJS', [CurrencySymbol] = N'ЅМ' WHERE [Country] = 'Tajikistan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'TZS', [CurrencySymbol] = N'Sh' WHERE [Country] = 'Tanzania';
UPDATE [DB_Countries] SET [CurrencyCode] = 'THB', [CurrencySymbol] = N'฿' WHERE [Country] = 'Thailand';
UPDATE [DB_Countries] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'₣' WHERE [Country] = 'Togo';
UPDATE [DB_Countries] SET [CurrencyCode] = 'TND', [CurrencySymbol] = N'د.ت' WHERE [Country] = 'Tunisia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'TRY', [CurrencySymbol] = N'₺' WHERE [Country] = 'Türkiye';
UPDATE [DB_Countries] SET [CurrencyCode] = 'UGX', [CurrencySymbol] = N'Sh' WHERE [Country] = 'Uganda';
UPDATE [DB_Countries] SET [CurrencyCode] = 'UAH', [CurrencySymbol] = N'₴' WHERE [Country] = 'Ukraine';
UPDATE [DB_Countries] SET [CurrencyCode] = 'GBP', [CurrencySymbol] = N'£' WHERE [Country] = 'United Kingdom';
UPDATE [DB_Countries] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE [Country] = 'United States';
UPDATE [DB_Countries] SET [CurrencyCode] = 'UYU', [CurrencySymbol] = N'$U' WHERE [Country] = 'Uruguay';
UPDATE [DB_Countries] SET [CurrencyCode] = 'UZS', [CurrencySymbol] = N'so''m' WHERE [Country] = 'Uzbekistan';
UPDATE [DB_Countries] SET [CurrencyCode] = 'VES', [CurrencySymbol] = N'Bs' WHERE [Country] = 'Venezuela';
UPDATE [DB_Countries] SET [CurrencyCode] = 'VND', [CurrencySymbol] = N'₫' WHERE [Country] = 'Viet Nam';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ILS', [CurrencySymbol] = N'₪' WHERE [Country] = 'West Bank and Gaza Strip';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ZMW', [CurrencySymbol] = N'ZK' WHERE [Country] = 'Zambia';
UPDATE [DB_Countries] SET [CurrencyCode] = 'ZWL', [CurrencySymbol] = N'Z$' WHERE [Country] = 'Zimbabwe';

-- Verify the update
SELECT Country, CurrencyCode, CurrencySymbol FROM [DB_Countries] WHERE CurrencyCode IS NOT NULL ORDER BY Country;
SELECT COUNT(*) AS CountriesWithCurrency FROM [DB_Countries] WHERE CurrencyCode IS NOT NULL;
