// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RosraApp.Data;

#nullable disable

namespace RosraApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706090000_AddRegistrationConsentFields")]
    partial class AddRegistrationConsentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
